# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(help_text="Don't forget to add http:// or https:// to the URL", unique=True),
        ),
    ]
